name: Build iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
      - name: Get packages
        run: flutter pub get
        working-directory: family_storage
      - name: Build IPA
        run: flutter build ipa --release --no-codesign
        working-directory: family_storage
      - uses: actions/upload-artifact@v4
        with:
          name: IPA
          path: family_storage/build/ios/ipa/*.ipa
